config/routes.rb
Rails.application.routes.draw do
 resources "contacts" do
  get '/address' => 'contacts#address'
  resources "addrs"
end
  root 'contacts#index'

  

end

app/models/addr.rb
class Addr < ActiveRecord::Base
	belongs_to :contact


	
end

app/models/contact.rb
class Contact < ActiveRecord::Base
	has_many :addrs
end

app/controllers/addrs_controller.rb
class AddrsController < ApplicationController
	def create
    @contact = Contact.find(params[:contact_id])
    @addr = @contact.addrs.create(addrs_params)
    redirect_to contact_path(@contact)
  end
 
  private
    def addrs_params
      params.require(:addr).permit(:address, :country)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
      @contacts = Contact.all
  end

  def new
  end
  

  def show
     @contact = Contact.find(params[:id])
     
  end

  def edit
    @contact = Contact.find(params[:id])
  end

  def create
  @contact = Contact.new(contact_params)
  @contact.save
  redirect_to @contact
  end
  def update
  @contact = Contact.find(params[:id])
 
  if @contact.update(contact_params)
    redirect_to @contact
  else
    render 'edit'
  end
  end
   def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy
 
    redirect_to contacts_path
  end

  private
  def contact_params
    params.require(:contact).permit(:firstname, :lastname, :email, :address, :country, :phone)
  end
end

app/helpers/addrs_helper.rb
module AddrsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_address.html.erb
<h2><center>Add another address:</center></h2>
<%= form_for([@contact, @contact.addrs.build]) do |f| %>
  <p><center>
  <%= f.label :address %>
    <%= f.text_area :address %>
    </center>
  </p>
  <p><center>
    <%= f.label :country %>
    <%= f.text_field :country%>
    </center>
  </p>
   <p><center>
    <%= f.label :phone %>
    <%= f.text_field :phone%>
    </center>
  </p>
  <p><center>
    <%= f.submit %>
    </center>
  </p>
<% end %>

app/views/contacts/_form.html.erb
<h1><center>New contacts</center></h1>
<%= form_for :contact, url: contacts_path do |f| %>
  <p><center>
    <%= f.label :firstname %>
    <%= f.text_field :firstname, placeholder: 'firstname' %>
    </center>  
  </p>
 
  <p><center>
    <%= f.label :lastname %>
    <%= f.text_field :lastname, placeholder: 'lastname' %>
    </center>
  </p>
   <p><center>
    <%= f.label :email %>
    <%= f.text_field :email, placeholder: 'user@domain.com' %>
    </center>
  </p>
   <p><center>
    <%= f.label :address %>
    <%= f.text_area :address, placeholder: 'address'  %>
    </center>

  </p>
  <p><center>
  <%= f.label :country%>
    <%= f.text_field :country, placeholder:'country'%>
    </center>
  </p>
 
  <p><center>
    <%= f.label :phone %>
    <%= f.text_field :phone, placeholder:'phone' %>
    </center>
  </p>
 
  <p><center>
    <%= f.submit %>
    </center>
  </p>
<% end %>

app/views/contacts/address.html.erb
<%= render 'address' %>

app/views/contacts/edit.html.erb
<%= render 'form' %>

app/views/contacts/index.html.erb
<h1>Listing contacts</h1>
 
<table class="table table-bordered">
<thead>
  <tr>
    <th>Firstname</th>
      <th>Lastname</th>
    
    <th>Email</th>
    <th>Address</th>
    <th>Country</th>
    <th>Phone</th>
  </tr>
  </thead>
 
  <% @contacts.each do |contact| %>
  <tbody>
    <tr>
    <td>
        <%=  contact.firstname %></td>
        <td><%=  contact.lastname %>
        
        </td>
     
      <td><%= contact.email %></td>
      <td><%= contact.address %></td>
      <td><%= contact.country %></td>
      <td><%= contact.phone %></td>
      
      <td><%= link_to '<button type="button" class="btn btn-info >show</button>'.html_safe, contact_path(contact)  %>

      <button type="button" class="btn btn-info">Show</button></td>
       <td><%= link_to '<button type="button" class="btn btn-danger >delete</button>'.html_safe, contact_path(contact),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
              <button type="button" class="btn btn-danger">Delete</button></td>
</td>
<td><%= link_to '<button type="button" class="btn btn-info >edit</button>'.html_safe, edit_contact_path(contact)  %>

      <button type="button" class="btn btn-info">edit</button></td>


    </tr>
  <% end %>
  </tbody>
</table>
<%= link_to '<button type="button" class="btn btn-primary >New Contact</button>'.html_safe, new_contact_path  %>
<button type="button" class="btn btn-primary">New Contact</button>
 <%= link_to '<button type="button" class="btn btn-primary >New Contact</button>'.html_safe,contacts_path  %>
<button type="button" class="btn btn-primary">AllContacts</button>

app/views/contacts/new.html.erb
<%= render 'form' %>

 <center><%= link_to '<button type="button" class="btn btn-primary >New Contact</button>'.html_safe,contacts_path  %></center>
<button type="button" class="btn btn-primary">AllContacts</button>

app/views/contacts/show.html.erb
<h1><center>Contacts</center></h1>

<p><center>
<strong>Firstname:</strong>
<%=  @contact.firstname %>
</center>
</p>
<p>
<center>
<strong>Lastname:</strong>
<%=  @contact.lastname %>
</center>
</p>
<p><center>
<strong>Email:</strong>
<%=  @contact.email %></p>
</center>
</p>
<p><center>
<strong>Address:</strong>
<%= @contact.address %>
</center>
</p>
<p><center>
<strong>Country:</strong>
<%= @contact.country %>
  
</center>
  
</p>
<p><center>
<strong>Phone:</strong>
  <%= @contact.phone %></center> 
</p>
 <% if @contact.addrs.present? %>

 <h><center>Another contact adress </center></h2>
 <% @contact.addrs.each do |address| %>
<p>
<center>
  <strong>Address:</strong>
  <%= address.address %>
  </center>
</p>
<p><center>
  <strong>Phone:</strong>
  <%= address.phone %></center>
</p>
<p><center>
  <strong>Country:</strong>
  <%= address.country %></center>
</p>
<% end %>
<% end %>

<%= render 'address' %>

 <center><%= link_to '<button type="button" class="btn btn-primary >New Contact</button>'.html_safe, new_contact_path  %></center>
<button type="button" class="btn btn-primary">New Contact</button>
 <%= link_to '<button type="button" class="btn btn-primary >New Contact</button>'.html_safe,contacts_path  %>
<button type="button" class="btn btn-primary">AllContacts</button>
<%= link_to '<button type="button" class="btn btn-primary >Back</button>'.html_safe,contacts_path  %>
<button type="button" class="btn btn-primary">Back</button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cms</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>